export { default as Home } from './Home/Home';
export { default as Header } from './Header/Header';
export { default as SubTotal } from './SubTotal/SubTotal';
export { default as Product } from './Product/Product';
export { default as LogIn } from './LogIn/Login';
export { default as CheckOut } from './CheckOut/Checkout';
export { default as Button } from './Button/Button';
export { default as Footer } from './Footer/Footer';
export { default as Payment } from './Payment/Payment';
