export { default as Logo } from './images/logo.png';
export { default as AmazonBanner } from './images/amazon-banner.jpg';
export {default as ProductLarge} from './images/prod-large.jpg';
export {default as ProductLarge1} from './images/prod-large1.jpg';
export {default as ProductLarge2} from './images/prod-large1.jpg';
export {default as Product0} from './images/product.jpg';
export {default as Product1} from './images/product1.jpg';
export {default as Product2} from './images/product2.jpg';
export {default as Product3} from './images/product3.jpg';
export {default as Product4} from './images/product4.jpg';
export {default as Product5} from './images/product5.jpg';
export {default as Product6} from './images/product6.jpg';
export {default as Product7} from './images/product7.jpg';
export {default as Product8} from './images/product8.jpg';
export {default as Product9} from './images/product9.jpg';
